-- V001: initial schema
-- This migration establishes the full baseline schema for EmailOps.
-- All statements use IF NOT EXISTS / IF NOT EXISTS so the migration is safe
-- to run on an existing database (e.g. a developer DB that predates refinery).
--
-- DO NOT edit this file after it has been applied to any database.
-- To add or change schema, create V002__description.sql etc.

-- Accounts table
CREATE TABLE IF NOT EXISTS accounts (
    id TEXT PRIMARY KEY,
    provider TEXT NOT NULL,
    email TEXT NOT NULL UNIQUE,
    name TEXT NOT NULL,
    created_at INTEGER NOT NULL,
    sort_order INTEGER NOT NULL DEFAULT 0,
    enabled INTEGER NOT NULL DEFAULT 1,
    sync_from_timestamp INTEGER
);

-- Emails table
CREATE TABLE IF NOT EXISTS emails (
    id TEXT PRIMARY KEY,
    account_id TEXT NOT NULL,
    thread_id TEXT NOT NULL,
    message_id TEXT,
    subject TEXT NOT NULL,
    sender TEXT NOT NULL,
    sender_email TEXT NOT NULL,
    sender_domain TEXT NOT NULL DEFAULT '',
    recipients_json TEXT NOT NULL,
    cc_json TEXT NOT NULL DEFAULT '[]',
    snippet TEXT NOT NULL,
    timestamp INTEGER NOT NULL,
    is_read INTEGER NOT NULL DEFAULT 0,
    is_deleted INTEGER NOT NULL DEFAULT 0,
    triage_status TEXT,
    category TEXT NOT NULL DEFAULT 'primary',
    -- Provider-side mailbox: 'inbox' (default), 'sent', 'spam', 'trash'.
    -- Drafts live in the separate `drafts` table and never appear here.
    mailbox TEXT NOT NULL DEFAULT 'inbox',
    raw_json TEXT,
    created_at INTEGER NOT NULL,
    FOREIGN KEY (account_id) REFERENCES accounts(id)
);

-- Per-pipeline extraction idempotency. One row means that pipeline has
-- processed the email, independently from any other extractor.
CREATE TABLE IF NOT EXISTS email_extraction_status (
    email_id TEXT NOT NULL,
    pipeline TEXT NOT NULL,
    extracted_at INTEGER NOT NULL,
    PRIMARY KEY (email_id, pipeline),
    FOREIGN KEY (email_id) REFERENCES emails(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_email_extraction_status_pipeline
    ON email_extraction_status(pipeline, extracted_at DESC);

-- Drafts table
CREATE TABLE IF NOT EXISTS drafts (
    id TEXT PRIMARY KEY,
    email_id TEXT,
    account_id TEXT NOT NULL,
    to_addresses_json TEXT NOT NULL,
    subject TEXT NOT NULL,
    body TEXT NOT NULL,
    ai_generated INTEGER NOT NULL DEFAULT 0,
    status TEXT NOT NULL DEFAULT 'draft',
    created_at INTEGER NOT NULL,
    updated_at INTEGER NOT NULL,
    FOREIGN KEY (email_id) REFERENCES emails(id),
    FOREIGN KEY (account_id) REFERENCES accounts(id)
);

CREATE INDEX IF NOT EXISTS idx_drafts_account ON drafts(account_id, status, updated_at DESC);

-- Email bodies stored separately so the emails table stays small and
-- list/filter queries never touch the large body column.
CREATE TABLE IF NOT EXISTS email_bodies (
    email_id TEXT PRIMARY KEY,
    body     TEXT NOT NULL DEFAULT '',
    FOREIGN KEY (email_id) REFERENCES emails(id) ON DELETE CASCADE
);

-- Sync state table
CREATE TABLE IF NOT EXISTS sync_state (
    account_id TEXT PRIMARY KEY,
    last_sync_at INTEGER,
    history_id TEXT,
    next_page_token TEXT,
    status TEXT NOT NULL DEFAULT 'idle',
    error TEXT,
    FOREIGN KEY (account_id) REFERENCES accounts(id)
);

-- Embedding chunks metadata (maps rowid -> email_id + chunk_index).
-- `account_id` is denormalized from `emails.account_id` so vec_search can
-- pre-filter rowids to a single account *before* the KNN scan, giving each
-- account an effectively independent vector store on top of the shared
-- `vec_emails` virtual table.
CREATE TABLE IF NOT EXISTS embedding_chunks (
    rowid INTEGER PRIMARY KEY AUTOINCREMENT,
    email_id TEXT NOT NULL,
    account_id TEXT NOT NULL DEFAULT '',
    chunk_index INTEGER NOT NULL DEFAULT 0,
    embedding_model TEXT NOT NULL,
    content_hash TEXT NOT NULL,
    created_at INTEGER NOT NULL,
    FOREIGN KEY (email_id) REFERENCES emails(id) ON DELETE CASCADE,
    UNIQUE(email_id, chunk_index)
);
CREATE INDEX IF NOT EXISTS idx_embedding_chunks_email ON embedding_chunks(email_id);
CREATE INDEX IF NOT EXISTS idx_embedding_chunks_account ON embedding_chunks(account_id);

-- Vector index (rowid matches embedding_chunks.rowid)
-- Uses cosine distance — similarity = 1.0 - distance, range [0, 1]
CREATE VIRTUAL TABLE IF NOT EXISTS vec_emails USING vec0(
    embedding float[768] distance_metric=cosine
);

-- Indexes for common queries
CREATE INDEX IF NOT EXISTS idx_emails_account_id ON emails(account_id);
CREATE INDEX IF NOT EXISTS idx_emails_thread_id ON emails(thread_id);
CREATE INDEX IF NOT EXISTS idx_emails_timestamp ON emails(timestamp DESC);
CREATE INDEX IF NOT EXISTS idx_emails_triage_status ON emails(triage_status);
CREATE INDEX IF NOT EXISTS idx_emails_category ON emails(category);
CREATE INDEX IF NOT EXISTS idx_emails_sender_email ON emails(account_id, sender_email);
-- Compound covering indexes for the main inbox query and unread counts
CREATE INDEX IF NOT EXISTS idx_emails_account_timestamp ON emails(account_id, timestamp DESC);
CREATE INDEX IF NOT EXISTS idx_emails_account_read ON emails(account_id, is_read, timestamp DESC);
-- Covering index for the primary inbox query: (account, not-deleted, newest-first).
-- Avoids a full account-scan before the is_deleted filter is applied.
CREATE INDEX IF NOT EXISTS idx_emails_account_active ON emails(account_id, is_deleted, timestamp DESC, id DESC);
CREATE INDEX IF NOT EXISTS idx_emails_account_mailbox
    ON emails(account_id, mailbox, is_deleted, timestamp DESC, id DESC);
-- Covering index for NOT EXISTS "latest in thread" correlated subquery.
CREATE INDEX IF NOT EXISTS idx_emails_thread_latest ON emails(account_id, thread_id, timestamp DESC, id DESC);
-- Covering indexes for filter-stats GROUP BY queries (domain and sender aggregation).
-- is_deleted is included so SQLite can answer entirely from the index without
-- touching the main table (avoids reading the huge body column on every row).
CREATE INDEX IF NOT EXISTS idx_emails_sender_domain ON emails(account_id, sender_domain, thread_id);
CREATE INDEX IF NOT EXISTS idx_emails_domain_stats ON emails(account_id, is_deleted, sender_domain);
CREATE INDEX IF NOT EXISTS idx_emails_sender_stats ON emails(account_id, is_deleted, sender_email);
-- Covering indexes for the domain/sender filter CTE (matched_threads step).
-- Including is_deleted + thread_id means step 1 is fully index-only: no body reads.
CREATE INDEX IF NOT EXISTS idx_emails_domain_filter ON emails(account_id, is_deleted, sender_domain, thread_id);
CREATE INDEX IF NOT EXISTS idx_emails_sender_filter ON emails(account_id, is_deleted, sender_email, thread_id);

-- Dev-mode token storage (bypasses OS keychain)
CREATE TABLE IF NOT EXISTS dev_tokens (
    account_id TEXT PRIMARY KEY,
    tokens_json TEXT NOT NULL,
    updated_at INTEGER NOT NULL
);

-- IMAP server settings persisted in the DB so they survive keychain loss.
-- The password lives only in the keychain (or dev_imap_creds in dev mode);
-- this table mirrors the non-secret fields so the re-auth dialog can always
-- pre-fill host/port/username/smtp settings even when the keychain entry is
-- missing — at which point the user only needs to retype their password.
CREATE TABLE IF NOT EXISTS imap_account_settings (
    account_id TEXT PRIMARY KEY,
    imap_host TEXT NOT NULL,
    imap_port INTEGER NOT NULL,
    imap_username TEXT NOT NULL,
    smtp_host TEXT NOT NULL,
    smtp_port INTEGER NOT NULL,
    FOREIGN KEY (account_id) REFERENCES accounts(id) ON DELETE CASCADE
);

-- Dev-mode IMAP credential storage (bypasses OS keychain)
CREATE TABLE IF NOT EXISTS dev_imap_creds (
    account_id TEXT PRIMARY KEY,
    creds_json TEXT NOT NULL,
    updated_at INTEGER NOT NULL
);

-- User preferences (key-value store)
CREATE TABLE IF NOT EXISTS user_preferences (
    key TEXT PRIMARY KEY,
    value TEXT NOT NULL
);

-- Trusted senders whose remote images should auto-load in the email view.
-- A row is only created when the user explicitly clicks "Always trust this
-- sender" on the blocked-images banner — never inferred from a one-off
-- "Show images" click.
CREATE TABLE IF NOT EXISTS trusted_senders (
    account_id TEXT NOT NULL,
    sender_email TEXT NOT NULL,
    created_at INTEGER NOT NULL,
    PRIMARY KEY (account_id, sender_email),
    FOREIGN KEY (account_id) REFERENCES accounts(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_trusted_senders_account ON trusted_senders(account_id);

-- Smart filter user preferences
CREATE TABLE IF NOT EXISTS smart_filter_prefs (
    id TEXT PRIMARY KEY,
    filter_type TEXT NOT NULL,
    filter_value TEXT NOT NULL,
    status TEXT NOT NULL,
    account_id TEXT NOT NULL,
    created_at INTEGER NOT NULL,
    FOREIGN KEY (account_id) REFERENCES accounts(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_smart_filter_prefs_account ON smart_filter_prefs(account_id);

-- Cached smart filter suggestions (persisted across restarts)
CREATE TABLE IF NOT EXISTS smart_filter_suggestions (
    id TEXT PRIMARY KEY,
    filter_type TEXT NOT NULL,
    filter_value TEXT NOT NULL,
    count INTEGER NOT NULL,
    account_id TEXT NOT NULL,
    calculated_at INTEGER NOT NULL,
    FOREIGN KEY (account_id) REFERENCES accounts(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_smart_filter_suggestions_account ON smart_filter_suggestions(account_id);

-- Full-text search index for hybrid search (FTS5)
-- Standalone (not external content) — owns its own data
CREATE VIRTUAL TABLE IF NOT EXISTS emails_fts USING fts5(
    email_id UNINDEXED,
    subject,
    sender,
    body,
    tokenize='porter unicode61'
);

-- FTS delete trigger only — INSERT and UPDATE handled manually in Rust
-- to strip HTML before indexing (SQL triggers cannot call Rust functions).
CREATE TRIGGER IF NOT EXISTS emails_fts_delete AFTER DELETE ON emails BEGIN
    DELETE FROM emails_fts WHERE email_id = old.id;
END;

-- Attachment classification rules (user-defined)
CREATE TABLE IF NOT EXISTS attachment_rules (
    id TEXT PRIMARY KEY,
    account_id TEXT NOT NULL,
    name TEXT NOT NULL,
    sender_email_pattern TEXT,
    subject_pattern TEXT,
    filename_pattern TEXT,
    tags_json TEXT NOT NULL DEFAULT '[]',
    enabled INTEGER NOT NULL DEFAULT 1,
    created_at INTEGER NOT NULL,
    updated_at INTEGER NOT NULL,
    FOREIGN KEY (account_id) REFERENCES accounts(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_attachment_rules_account ON attachment_rules(account_id);

-- Downloaded attachments (matched by rules during sync)
CREATE TABLE IF NOT EXISTS attachments (
    id TEXT PRIMARY KEY,
    account_id TEXT NOT NULL,
    email_id TEXT NOT NULL,
    rule_id TEXT NOT NULL,
    gmail_attachment_id TEXT NOT NULL,
    filename TEXT NOT NULL,
    mime_type TEXT NOT NULL,
    file_size INTEGER NOT NULL,
    file_path TEXT NOT NULL,
    tags_json TEXT NOT NULL DEFAULT '[]',
    sender_email TEXT NOT NULL,
    subject TEXT NOT NULL,
    email_timestamp INTEGER NOT NULL,
    created_at INTEGER NOT NULL,
    FOREIGN KEY (account_id) REFERENCES accounts(id) ON DELETE CASCADE,
    FOREIGN KEY (email_id) REFERENCES emails(id) ON DELETE CASCADE,
    FOREIGN KEY (rule_id) REFERENCES attachment_rules(id) ON DELETE CASCADE
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_attachments_dedup_filename ON attachments(email_id, filename, rule_id);
CREATE INDEX IF NOT EXISTS idx_attachments_account ON attachments(account_id);
CREATE INDEX IF NOT EXISTS idx_attachments_rule ON attachments(rule_id);
CREATE INDEX IF NOT EXISTS idx_attachments_email ON attachments(email_id);
CREATE INDEX IF NOT EXISTS idx_attachments_timestamp ON attachments(email_timestamp DESC);

-- Email classification tags (many-to-many, one value per type per email)
CREATE TABLE IF NOT EXISTS email_tags (
    email_id TEXT NOT NULL,
    tag_type TEXT NOT NULL,
    tag_value TEXT NOT NULL,
    confidence REAL,
    created_at INTEGER NOT NULL,
    PRIMARY KEY (email_id, tag_type),
    FOREIGN KEY (email_id) REFERENCES emails(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_email_tags_type_value ON email_tags(tag_type, tag_value);
CREATE INDEX IF NOT EXISTS idx_email_tags_email ON email_tags(email_id);

-- Classification rules (user-configurable, rule-based pre-classification)
CREATE TABLE IF NOT EXISTS classification_rules (
    id TEXT PRIMARY KEY,
    account_id TEXT NOT NULL,
    name TEXT NOT NULL,
    sender_pattern TEXT,
    subject_pattern TEXT,
    priority TEXT NOT NULL DEFAULT 'low',
    intent TEXT NOT NULL DEFAULT 'notification',
    topic TEXT NOT NULL DEFAULT 'operations',
    enabled INTEGER NOT NULL DEFAULT 1,
    created_at INTEGER NOT NULL,
    updated_at INTEGER NOT NULL,
    FOREIGN KEY (account_id) REFERENCES accounts(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_classification_rules_account ON classification_rules(account_id);

-- AI provider configuration
CREATE TABLE IF NOT EXISTS ai_config (
    id INTEGER PRIMARY KEY CHECK (id = 1),
    provider TEXT NOT NULL DEFAULT 'ollama',
    model TEXT NOT NULL DEFAULT 'gemma4:e2b',
    api_key_id TEXT,
    monthly_budget_usd REAL NOT NULL DEFAULT 0.0,
    period_start INTEGER NOT NULL DEFAULT 0,
    is_active INTEGER NOT NULL DEFAULT 1
);

-- AI usage tracking (per call)
CREATE TABLE IF NOT EXISTS ai_usage (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    provider TEXT NOT NULL,
    model TEXT NOT NULL,
    operation TEXT NOT NULL,
    prompt_tokens INTEGER NOT NULL DEFAULT 0,
    completion_tokens INTEGER NOT NULL DEFAULT 0,
    cost_usd REAL NOT NULL DEFAULT 0.0,
    timestamp INTEGER NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_ai_usage_timestamp ON ai_usage(timestamp);
CREATE INDEX IF NOT EXISTS idx_ai_usage_provider ON ai_usage(provider);

-- Failed email download tracking (retry on next sync to fill gaps)
CREATE TABLE IF NOT EXISTS sync_failed_emails (
    email_id TEXT NOT NULL,
    account_id TEXT NOT NULL,
    failed_at INTEGER NOT NULL,
    retry_count INTEGER NOT NULL DEFAULT 0,
    last_error TEXT,
    PRIMARY KEY (email_id, account_id),
    FOREIGN KEY (account_id) REFERENCES accounts(id) ON DELETE CASCADE
);

-- Attachment metadata discovered during sync (all attachments, not just rule-matched ones)
CREATE TABLE IF NOT EXISTS email_attachment_meta (
    id TEXT PRIMARY KEY,
    email_id TEXT NOT NULL,
    account_id TEXT NOT NULL,
    provider_attachment_id TEXT NOT NULL DEFAULT '',
    filename TEXT NOT NULL,
    mime_type TEXT NOT NULL,
    file_size INTEGER NOT NULL DEFAULT 0,
    file_path TEXT,
    -- IMAP providers embed attachment bytes inline rather than offering a
    -- separate fetch. Stored base64 here so they can be served the same way
    -- as Gmail/Graph fetched-on-demand attachments.
    inline_data TEXT,
    FOREIGN KEY (email_id) REFERENCES emails(id) ON DELETE CASCADE,
    FOREIGN KEY (account_id) REFERENCES accounts(id) ON DELETE CASCADE
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_email_attachment_meta_dedup ON email_attachment_meta(email_id, filename);
CREATE INDEX IF NOT EXISTS idx_email_attachment_meta_email ON email_attachment_meta(email_id);

-- Chat conversations (scoped per account)
CREATE TABLE IF NOT EXISTS chat_conversations (
    id TEXT PRIMARY KEY,
    account_id TEXT NOT NULL,
    title TEXT NOT NULL,
    created_at INTEGER NOT NULL,
    updated_at INTEGER NOT NULL,
    FOREIGN KEY (account_id) REFERENCES accounts(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_chat_conv_account ON chat_conversations(account_id, updated_at DESC);

-- Chat messages (user + assistant turns). role is 'user' | 'assistant' | 'system'.
CREATE TABLE IF NOT EXISTS chat_messages (
    id TEXT PRIMARY KEY,
    conversation_id TEXT NOT NULL,
    role TEXT NOT NULL,
    content TEXT NOT NULL,
    model TEXT,
    token_count INTEGER,
    latency_ms INTEGER,
    -- JSON ChatTrace: routing decision, retrieval stats, tool calls, timing.
    -- Nullable: pre-trace messages and non-assistant rows have no trace.
    trace TEXT,
    created_at INTEGER NOT NULL,
    FOREIGN KEY (conversation_id) REFERENCES chat_conversations(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_chat_msg_conv ON chat_messages(conversation_id, created_at);

-- Citations: links an assistant message to the source emails it used.
-- Denormalized email metadata so the UI can render sources without extra queries.
CREATE TABLE IF NOT EXISTS chat_message_sources (
    message_id TEXT NOT NULL,
    citation_number INTEGER NOT NULL,
    email_id TEXT NOT NULL,
    relevance_score REAL,
    subject TEXT NOT NULL DEFAULT '',
    sender TEXT NOT NULL DEFAULT '',
    sender_email TEXT NOT NULL DEFAULT '',
    email_timestamp INTEGER NOT NULL DEFAULT 0,
    -- The chunk of body text that was fed to the LLM for this citation. Lets
    -- the "sources used" panel show exactly what the model saw.
    body_excerpt TEXT,
    PRIMARY KEY (message_id, citation_number),
    FOREIGN KEY (message_id) REFERENCES chat_messages(id) ON DELETE CASCADE,
    FOREIGN KEY (email_id) REFERENCES emails(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_chat_sources_message ON chat_message_sources(message_id);

-- ── Memory subsystem ─────────────────────────────────────────────────────────
-- Durable agent memory: user-profile facts, contact/domain/project notes.
-- Candidates start with status='candidate' and get promoted by the dream job.
CREATE TABLE IF NOT EXISTS memory_facts (
    id TEXT PRIMARY KEY,
    account_id TEXT NOT NULL,
    -- 'user' (self), 'contact' (single email), 'domain' (all @domain), 'project' (slug)
    subject_kind TEXT NOT NULL,
    -- For 'user': 'self'. For 'contact': email. For 'domain': domain. For 'project': slug.
    subject_key TEXT NOT NULL,
    -- Single declarative sentence. Kept short so multiple facts fit in the header.
    fact TEXT NOT NULL,
    -- 'extraction' (from email), 'user' (explicit remember), 'consolidation' (dream merge)
    source TEXT NOT NULL DEFAULT 'extraction',
    source_email_id TEXT,
    confidence REAL NOT NULL DEFAULT 0.6,
    -- Promotion score: accrues via recall hits + corroboration. >= threshold => promoted.
    score REAL NOT NULL DEFAULT 0.0,
    -- 'candidate' | 'promoted' | 'retired'
    status TEXT NOT NULL DEFAULT 'candidate',
    last_used_at INTEGER,
    -- Life-context classification set by the extractor: 'personal' | 'professional' | NULL.
    domain TEXT,
    -- Temporal classification: 'atemporal' (stable) | 'deciduous' (short-lived) | NULL.
    vigency TEXT,
    -- Company tag derived from the recipient domain stem (most frequent when
    -- multiple recipients). Lowercased, TLD stripped. NULL for non-extracted /
    -- older rows. Drives the company quick-filter in the Memory view.
    company TEXT,
    created_at INTEGER NOT NULL,
    updated_at INTEGER NOT NULL,
    FOREIGN KEY (account_id) REFERENCES accounts(id) ON DELETE CASCADE,
    FOREIGN KEY (source_email_id) REFERENCES emails(id) ON DELETE SET NULL
);
CREATE INDEX IF NOT EXISTS idx_memory_facts_subject
    ON memory_facts(account_id, subject_kind, subject_key, status);
CREATE INDEX IF NOT EXISTS idx_memory_facts_status
    ON memory_facts(account_id, status, score DESC);
CREATE INDEX IF NOT EXISTS idx_memory_facts_company
    ON memory_facts(account_id, company) WHERE company IS NOT NULL;

-- Per-thread computed state. Updated by implicit user-action triggers and the
-- extractor. Persisted so the agent reads a single row instead of replaying a thread.
CREATE TABLE IF NOT EXISTS thread_states (
    account_id TEXT NOT NULL,
    thread_id TEXT NOT NULL,
    -- 'user' = awaiting a reply from the user; 'them' = waiting on someone else;
    -- 'resolved' = closed out; 'unknown' = not yet classified.
    awaiting TEXT NOT NULL DEFAULT 'unknown',
    last_inbound_at INTEGER,
    last_outbound_at INTEGER,
    last_touched_at INTEGER NOT NULL,
    summary TEXT,
    -- Latest commitment/promise extracted from the thread (nullable).
    commitment TEXT,
    deadline_at INTEGER,
    -- JSON array of email addresses on the thread, de-duplicated.
    participants_json TEXT NOT NULL DEFAULT '[]',
    updated_at INTEGER NOT NULL,
    PRIMARY KEY (account_id, thread_id),
    FOREIGN KEY (account_id) REFERENCES accounts(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_thread_states_awaiting
    ON thread_states(account_id, awaiting, last_touched_at DESC);
CREATE INDEX IF NOT EXISTS idx_thread_states_deadline
    ON thread_states(account_id, deadline_at) WHERE deadline_at IS NOT NULL;

-- Action items: extracted from emails, surfaced from chat, or added by user.
CREATE TABLE IF NOT EXISTS pending_tasks (
    id TEXT PRIMARY KEY,
    account_id TEXT NOT NULL,
    title TEXT NOT NULL,
    detail TEXT,
    -- 'extracted' (from email), 'chat' (agent created), 'user' (manual)
    source TEXT NOT NULL DEFAULT 'extracted',
    source_email_id TEXT,
    source_thread_id TEXT,
    -- 'me' or an email address
    assignee TEXT NOT NULL DEFAULT 'me',
    -- 'open' | 'done' | 'snoozed' | 'dismissed'
    status TEXT NOT NULL DEFAULT 'open',
    -- 'low' | 'normal' | 'high'
    priority TEXT NOT NULL DEFAULT 'normal',
    due_at INTEGER,
    completed_at INTEGER,
    -- Company tag derived from recipient domain. See memory_facts.company.
    company TEXT,
    created_at INTEGER NOT NULL,
    updated_at INTEGER NOT NULL,
    FOREIGN KEY (account_id) REFERENCES accounts(id) ON DELETE CASCADE,
    FOREIGN KEY (source_email_id) REFERENCES emails(id) ON DELETE SET NULL
);
CREATE INDEX IF NOT EXISTS idx_pending_tasks_open
    ON pending_tasks(account_id, status, due_at, priority);
CREATE INDEX IF NOT EXISTS idx_pending_tasks_thread
    ON pending_tasks(source_thread_id);
CREATE INDEX IF NOT EXISTS idx_pending_tasks_email
    ON pending_tasks(source_email_id);
CREATE INDEX IF NOT EXISTS idx_pending_tasks_company
    ON pending_tasks(account_id, company) WHERE company IS NOT NULL;

-- Short-lived action log used as recency signal for the header and as raw
-- material for the dream consolidation job. Pruned after 30 days.
CREATE TABLE IF NOT EXISTS interaction_events (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    account_id TEXT NOT NULL,
    -- 'read' | 'reply' | 'draft' | 'tag' | 'search' | 'chat_turn' | 'archive'
    kind TEXT NOT NULL,
    email_id TEXT,
    thread_id TEXT,
    payload_json TEXT,
    created_at INTEGER NOT NULL,
    FOREIGN KEY (account_id) REFERENCES accounts(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_interaction_events_recent
    ON interaction_events(account_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_interaction_events_thread
    ON interaction_events(thread_id, created_at DESC);

-- Embeddings for memory_facts (mirrors vec_emails/embedding_chunks exactly).
-- One chunk per fact (facts are short; no need to split).
CREATE TABLE IF NOT EXISTS memory_fact_chunks (
    rowid INTEGER PRIMARY KEY AUTOINCREMENT,
    fact_id TEXT NOT NULL UNIQUE,
    embedding_model TEXT NOT NULL,
    created_at INTEGER NOT NULL,
    FOREIGN KEY (fact_id) REFERENCES memory_facts(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_memory_fact_chunks_fact ON memory_fact_chunks(fact_id);

CREATE VIRTUAL TABLE IF NOT EXISTS vec_memory_facts USING vec0(
    embedding float[768] distance_metric=cosine
);

-- Full-text search over facts. Mirrors emails_fts pattern.
CREATE VIRTUAL TABLE IF NOT EXISTS memory_facts_fts USING fts5(
    fact_id UNINDEXED,
    fact,
    subject_key,
    tokenize='porter unicode61'
);

-- Delete trigger only — INSERT/UPDATE handled manually in Rust for consistency
-- with emails_fts_delete (and so we can skip FTS writes during bulk imports).
CREATE TRIGGER IF NOT EXISTS memory_facts_fts_delete AFTER DELETE ON memory_facts BEGIN
    DELETE FROM memory_facts_fts WHERE fact_id = old.id;
END;

-- Tag priority scoring. Raw signals only (sent_count, received_count,
-- last_activity_at); the priority score is computed at query time so the
-- weights can be tuned without a migration. Updated incrementally from
-- services::tag_priority::update_from_new_emails after each sync batch --
-- only touches tags that appear on the newly-synced emails.
CREATE TABLE IF NOT EXISTS tag_priority (
    account_id        TEXT    NOT NULL,
    tag_type          TEXT    NOT NULL,
    tag_value         TEXT    NOT NULL,
    sent_count        INTEGER NOT NULL DEFAULT 0,
    received_count    INTEGER NOT NULL DEFAULT 0,
    last_activity_at  INTEGER,
    updated_at        INTEGER NOT NULL,
    PRIMARY KEY (account_id, tag_type, tag_value),
    FOREIGN KEY (account_id) REFERENCES accounts(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_tag_priority_account_type
    ON tag_priority(account_id, tag_type, last_activity_at DESC);

-- ── Lenses ──────────────────────────────────────────────────────────────────
-- User-defined or built-in AI-powered views of the mailbox.
-- See docs/lenses-prd.md for the full design.
CREATE TABLE IF NOT EXISTS lenses (
    id              TEXT PRIMARY KEY,
    name            TEXT NOT NULL,
    icon            TEXT,
    template_key    TEXT,
    account_id      TEXT,
    scope_json      TEXT NOT NULL,
    schema_json     TEXT NOT NULL,
    prompt_text     TEXT NOT NULL,
    prompt_version  INTEGER NOT NULL DEFAULT 1,
    model_provider  TEXT,
    model_name      TEXT,
    is_enabled      INTEGER NOT NULL DEFAULT 1,
    sort_order      INTEGER NOT NULL DEFAULT 0,
    created_at      INTEGER NOT NULL,
    updated_at      INTEGER NOT NULL,
    FOREIGN KEY (account_id) REFERENCES accounts(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_lenses_enabled_order ON lenses(is_enabled, sort_order);

-- Extracted rows: one per (lens, email).
-- extracted_json is the model output; overrides_json holds user edits and is
-- never clobbered on re-extraction (merged at read time in the service layer).
CREATE TABLE IF NOT EXISTS lens_rows (
    lens_id          TEXT NOT NULL,
    email_id         TEXT NOT NULL,
    account_id       TEXT NOT NULL,
    extracted_json   TEXT NOT NULL,
    overrides_json   TEXT,
    prompt_version   INTEGER NOT NULL,
    email_timestamp  INTEGER NOT NULL,
    extracted_at     INTEGER NOT NULL,
    status           TEXT NOT NULL DEFAULT 'ok',
    error_message    TEXT,
    PRIMARY KEY (lens_id, email_id),
    FOREIGN KEY (lens_id) REFERENCES lenses(id) ON DELETE CASCADE,
    FOREIGN KEY (email_id) REFERENCES emails(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_lens_rows_lens_recency ON lens_rows(lens_id, email_timestamp DESC);
CREATE INDEX IF NOT EXISTS idx_lens_rows_lens_status ON lens_rows(lens_id, status);

-- Rows the user explicitly removed from a Lens. Survives re-extraction even
-- when no lens_rows entry exists for the email yet.
CREATE TABLE IF NOT EXISTS lens_exclusions (
    lens_id     TEXT NOT NULL,
    email_id    TEXT NOT NULL,
    excluded_at INTEGER NOT NULL,
    PRIMARY KEY (lens_id, email_id),
    FOREIGN KEY (lens_id) REFERENCES lenses(id) ON DELETE CASCADE,
    FOREIGN KEY (email_id) REFERENCES emails(id) ON DELETE CASCADE
);

-- Run history for progress/debugging.
-- `total` is the scope size known up-front (0 when unknown, e.g. legacy rows).
CREATE TABLE IF NOT EXISTS lens_runs (
    id              TEXT PRIMARY KEY,
    lens_id         TEXT NOT NULL,
    kind            TEXT NOT NULL,
    started_at      INTEGER NOT NULL,
    finished_at     INTEGER,
    status          TEXT NOT NULL,
    processed       INTEGER NOT NULL DEFAULT 0,
    total           INTEGER NOT NULL DEFAULT 0,
    succeeded       INTEGER NOT NULL DEFAULT 0,
    failed          INTEGER NOT NULL DEFAULT 0,
    error_message   TEXT,
    FOREIGN KEY (lens_id) REFERENCES lenses(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_lens_runs_lens_started ON lens_runs(lens_id, started_at DESC);
