//! Pure planner for the optimistic local Sent row inserted right after a
//! provider accepts a send. No I/O — the executor (`send.rs`) pre-generates
//! the uuid and timestamp, calls [`build_optimistic_sent_email`], and writes
//! the result via `Database::insert_sent_email_local`.
//!
//! Two shapes come out of the planner:
//! - **Provider-keyed row** (Gmail): the send response carried the canonical
//!   message id, so the row uses it as its primary key. The sync layer's
//!   existing-id dedup then never re-downloads it — this row IS the permanent
//!   copy (`pending_sync = false`), optionally upgraded in the background by
//!   an authoritative `get_message` fetch.
//! - **Synthetic pending row** (Outlook / IMAP): no provider id is known at
//!   send time, so the row gets a `local-sent-<uuid>` id and
//!   `pending_sync = true`; the sync reconciler replaces it when the real
//!   Sent copy is ingested.

use crate::models::{Account, Email};
use crate::sync::provider::{EmailBody, SentMessageMeta};

/// Prefix for synthetic optimistic row ids, so they are recognizable in
/// debugging sessions and can never collide with provider message ids.
pub const LOCAL_SENT_ID_PREFIX: &str = "local-sent-";

/// Maximum snippet length, mirroring what providers produce (~200 chars).
const SNIPPET_MAX_CHARS: usize = 200;

/// Everything the planner needs; no I/O. `synthetic_id` (the uuid part only,
/// prefixing is the planner's job) and `now_secs` are pre-generated by the
/// executor so the planner stays pure and table-testable.
pub struct OptimisticSendInput<'a> {
    pub account: &'a Account,
    pub to: &'a [String],
    pub cc: &'a [String],
    /// Raw subject as the user typed it. For replies the planner applies the
    /// same `Re: ` normalization as the wire subject.
    pub subject: &'a str,
    /// Body with language + footer flags already resolved by the send service.
    pub body: &'a EmailBody,
    /// `Some(thread_id)` for replies, `None` for new mail.
    pub reply_to_thread_id: Option<&'a str>,
    pub meta: &'a SentMessageMeta,
    /// Pre-generated uuid (without the `local-sent-` prefix).
    pub synthetic_uuid: &'a str,
    pub now_secs: i64,
}

pub struct OptimisticSentEmail {
    pub email: Email,
    /// True when the row must be reconciled against the provider's Sent copy
    /// on a later sync (no provider message id was available at send time).
    pub pending_sync: bool,
}

/// Build the local Sent row for a just-accepted send.
pub fn build_optimistic_sent_email(input: &OptimisticSendInput<'_>) -> OptimisticSentEmail {
    let id = match &input.meta.provider_message_id {
        Some(provider_id) => provider_id.clone(),
        None => format!("{}{}", LOCAL_SENT_ID_PREFIX, input.synthetic_uuid),
    };
    let pending_sync = input.meta.provider_message_id.is_none();

    let thread_id = input
        .meta
        .provider_thread_id
        .clone()
        .or_else(|| input.reply_to_thread_id.map(str::to_string))
        .unwrap_or_else(|| id.clone());

    let subject = match input.reply_to_thread_id {
        Some(_) => crate::sync::mime_builder::reply_subject(input.subject),
        None => input.subject.to_string(),
    };

    // Store the body with the footer baked in, matching what the provider's
    // Sent copy will contain (the footer is appended at the MIME/payload
    // layer on the wire).
    let body = match input.body.html.as_deref() {
        Some(html) => format!("{}{}", html, input.body.footer_html()),
        None => format!("{}{}", input.body.text, input.body.footer_plain()),
    };
    let snippet = snippet_from_text(&format!("{}{}", input.body.text, input.body.footer_plain()));

    OptimisticSentEmail {
        email: Email {
            id,
            account_id: input.account.id.clone(),
            thread_id,
            message_id: input.meta.message_id_header.clone(),
            subject,
            sender: input.account.name.clone(),
            sender_email: input.account.email.clone(),
            recipients: input.to.to_vec(),
            cc: input.cc.to_vec(),
            body,
            snippet,
            timestamp: input.now_secs,
            is_read: true,
            triage_status: None,
            category: "primary".to_string(),
            mailbox: "sent".to_string(),
        },
        pending_sync,
    }
}

/// First ~200 chars of the plain text with whitespace collapsed, mirroring
/// provider-produced snippets.
fn snippet_from_text(text: &str) -> String {
    let collapsed: String = text.split_whitespace().collect::<Vec<_>>().join(" ");
    collapsed.chars().take(SNIPPET_MAX_CHARS).collect()
}

#[cfg(test)]
mod tests {
    use super::*;

    fn account() -> Account {
        Account {
            id: "acc-1".to_string(),
            provider: "gmail".to_string(),
            email: "me@example.com".to_string(),
            name: "Me Myself".to_string(),
            created_at: 0,
            sort_order: 0,
            enabled: true,
            sync_from_timestamp: None,
        }
    }

    fn input<'a>(
        account: &'a Account,
        body: &'a EmailBody,
        meta: &'a SentMessageMeta,
        reply_to_thread_id: Option<&'a str>,
    ) -> OptimisticSendInput<'a> {
        static TO: std::sync::LazyLock<Vec<String>> = std::sync::LazyLock::new(|| vec!["them@example.com".into()]);
        OptimisticSendInput {
            account,
            to: &TO,
            cc: &[],
            subject: "Quarterly report",
            body,
            reply_to_thread_id,
            meta,
            synthetic_uuid: "u-123",
            now_secs: 1_700_000_000,
        }
    }

    #[test]
    fn gmail_meta_uses_provider_ids_and_is_not_pending() {
        let acc = account();
        let body = EmailBody::plain("here it is");
        let meta = SentMessageMeta {
            provider_message_id: Some("gm-1".into()),
            provider_thread_id: Some("gt-1".into()),
            message_id_header: Some("<mid@local>".into()),
        };
        let out = build_optimistic_sent_email(&input(&acc, &body, &meta, Some("local-thread")));
        assert_eq!(out.email.id, "gm-1");
        assert_eq!(out.email.thread_id, "gt-1", "provider thread id wins over local");
        assert_eq!(out.email.message_id.as_deref(), Some("<mid@local>"));
        assert!(!out.pending_sync, "provider-keyed rows are permanent");
    }

    #[test]
    fn no_provider_id_yields_synthetic_pending_row() {
        let acc = account();
        let body = EmailBody::plain("here it is");
        let meta = SentMessageMeta::default();
        let out = build_optimistic_sent_email(&input(&acc, &body, &meta, None));
        assert_eq!(out.email.id, "local-sent-u-123");
        assert!(out.pending_sync);
    }

    #[test]
    fn reply_uses_local_thread_id_when_meta_has_none() {
        let acc = account();
        let body = EmailBody::plain("x");
        let meta = SentMessageMeta::default();
        let out = build_optimistic_sent_email(&input(&acc, &body, &meta, Some("thread-9")));
        assert_eq!(out.email.thread_id, "thread-9");
    }

    #[test]
    fn new_mail_without_meta_threads_under_its_own_id() {
        let acc = account();
        let body = EmailBody::plain("x");
        let meta = SentMessageMeta::default();
        let out = build_optimistic_sent_email(&input(&acc, &body, &meta, None));
        assert_eq!(out.email.thread_id, out.email.id, "fresh mail starts its own thread");
    }

    #[test]
    fn reply_subject_gets_re_prefix_once() {
        let acc = account();
        let body = EmailBody::plain("x");
        let meta = SentMessageMeta::default();
        let out = build_optimistic_sent_email(&input(&acc, &body, &meta, Some("t")));
        assert_eq!(out.email.subject, "Re: Quarterly report");

        let mut inp = input(&acc, &body, &meta, Some("t"));
        inp.subject = "RE: Quarterly report";
        let out = build_optimistic_sent_email(&inp);
        assert_eq!(out.email.subject, "RE: Quarterly report", "existing prefix kept as-is");
    }

    #[test]
    fn new_mail_subject_is_untouched() {
        let acc = account();
        let body = EmailBody::plain("x");
        let meta = SentMessageMeta::default();
        let out = build_optimistic_sent_email(&input(&acc, &body, &meta, None));
        assert_eq!(out.email.subject, "Quarterly report");
    }

    #[test]
    fn sender_fields_come_from_the_account_and_mailbox_is_sent() {
        let acc = account();
        let body = EmailBody::plain("x");
        let meta = SentMessageMeta::default();
        let out = build_optimistic_sent_email(&input(&acc, &body, &meta, None));
        assert_eq!(out.email.sender, "Me Myself");
        assert_eq!(
            out.email.sender_email, "me@example.com",
            "drives the Sent view predicate"
        );
        assert_eq!(out.email.mailbox, "sent");
        assert!(out.email.is_read, "own sent mail is never unread");
        assert_eq!(out.email.timestamp, 1_700_000_000);
        assert_eq!(out.email.recipients, vec!["them@example.com"]);
    }

    #[test]
    fn plain_body_is_stored_with_plain_footer() {
        let acc = account();
        let body = EmailBody::plain("the body");
        let meta = SentMessageMeta::default();
        let out = build_optimistic_sent_email(&input(&acc, &body, &meta, None));
        assert!(out.email.body.starts_with("the body"));
        assert!(
            out.email.body.contains("Sent with EmailOps"),
            "footer baked into the stored body to match the wire copy"
        );
    }

    #[test]
    fn html_body_is_stored_with_html_footer() {
        let acc = account();
        let body = EmailBody::with_html("plain alt", "<p>rich</p>");
        let meta = SentMessageMeta::default();
        let out = build_optimistic_sent_email(&input(&acc, &body, &meta, None));
        assert!(out.email.body.starts_with("<p>rich</p>"));
        assert!(out.email.body.contains("getemailops.com"), "HTML footer appended");
        assert!(
            out.email.snippet.starts_with("plain alt"),
            "snippet comes from the plain text, not the HTML"
        );
    }

    #[test]
    fn footer_free_body_is_stored_without_footer() {
        let acc = account();
        let body = EmailBody::plain("draft-ish").without_footer();
        let meta = SentMessageMeta::default();
        let out = build_optimistic_sent_email(&input(&acc, &body, &meta, None));
        assert!(!out.email.body.contains("Sent with EmailOps"));
    }

    #[test]
    fn snippet_collapses_whitespace_and_truncates() {
        let acc = account();
        let long = format!("word  with\n\nbreaks {}", "x".repeat(300));
        let body = EmailBody::plain(long).without_footer();
        let meta = SentMessageMeta::default();
        let out = build_optimistic_sent_email(&input(&acc, &body, &meta, None));
        assert!(out.email.snippet.starts_with("word with breaks"));
        assert!(out.email.snippet.chars().count() <= 200);
    }
}
